create database  cars2 charset=utf8;

use cars2;
/* Drop Tables */

DROP TABLE CAR;

/* Create Tables */

CREATE TABLE CAR
(
	CARID INT NOT NULL AUTO_INCREMENT,
	PINPAIMING VARCHAR(20),
	XIELIE VARCHAR(20),
	GONGLISHU INT,
	YANSE VARCHAR(20),
	SHOUJIA INT,
	NIANFEN VARCHAR(20),
	SUOZAIDI VARCHAR(20),
	TUPIAN VARCHAR(200),
	PRIMARY KEY (CARID)
) charset=utf8;

CREATE TABLE USER
(   USERNAME INT NOT NULL AUTO_INCREMENT,
    USERSEX VARCHAR(10) NOT NULL,
    USERADDRESS VARCHAR(40) NOT NULL,
    PRIMARY KEY(USERNAME)
) charset=utf8;


CREATE TABLE ADMINUSER
(   USERID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    PRIMARY KEY(USERID)
) charset=utf8;



