package com.oracle.cars.model;

import java.io.Serializable;

/**
 * car ���f���N���X.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Car implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** carid. */
	private Integer carid;

	/** pinpaiming. */
	private String pinpaiming;

	/** xielie. */
	private String xielie;

	/** gonglishu. */
	private Integer gonglishu;

	/** yanse. */
	private String yanse;

	/** shoujia. */
	private Integer shoujia;

	/** nianfen. */
	private String nianfen;

	/** suozaidi. */
	private String suozaidi;

	/** tupian. */
	private String tupian;

	/**
	 * �R���X�g���N�^.
	 */
	public Car() {
	}

	/**
	 * carid ��ݒ肵�܂�.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * carid ���擾���܂�.
	 * 
	 * @return carid
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * pinpaiming ��ݒ肵�܂�.
	 * 
	 * @param pinpaiming
	 *            pinpaiming
	 */
	public void setPinpaiming(String pinpaiming) {
		this.pinpaiming = pinpaiming;
	}

	/**
	 * pinpaiming ���擾���܂�.
	 * 
	 * @return pinpaiming
	 */
	public String getPinpaiming() {
		return this.pinpaiming;
	}

	/**
	 * xielie ��ݒ肵�܂�.
	 * 
	 * @param xielie
	 *            xielie
	 */
	public void setXielie(String xielie) {
		this.xielie = xielie;
	}

	/**
	 * xielie ���擾���܂�.
	 * 
	 * @return xielie
	 */
	public String getXielie() {
		return this.xielie;
	}

	/**
	 * gonglishu ��ݒ肵�܂�.
	 * 
	 * @param gonglishu
	 *            gonglishu
	 */
	public void setGonglishu(Integer gonglishu) {
		this.gonglishu = gonglishu;
	}

	/**
	 * gonglishu ���擾���܂�.
	 * 
	 * @return gonglishu
	 */
	public Integer getGonglishu() {
		return this.gonglishu;
	}

	/**
	 * yanse ��ݒ肵�܂�.
	 * 
	 * @param yanse
	 *            yanse
	 */
	public void setYanse(String yanse) {
		this.yanse = yanse;
	}

	/**
	 * yanse ���擾���܂�.
	 * 
	 * @return yanse
	 */
	public String getYanse() {
		return this.yanse;
	}

	/**
	 * shoujia ��ݒ肵�܂�.
	 * 
	 * @param shoujia
	 *            shoujia
	 */
	public void setShoujia(Integer shoujia) {
		this.shoujia = shoujia;
	}

	/**
	 * shoujia ���擾���܂�.
	 * 
	 * @return shoujia
	 */
	public Integer getShoujia() {
		return this.shoujia;
	}

	/**
	 * nianfen ��ݒ肵�܂�.
	 * 
	 * @param nianfen
	 *            nianfen
	 */
	public void setNianfen(String nianfen) {
		this.nianfen = nianfen;
	}

	/**
	 * nianfen ���擾���܂�.
	 * 
	 * @return nianfen
	 */
	public String getNianfen() {
		return this.nianfen;
	}

	/**
	 * suozaidi ��ݒ肵�܂�.
	 * 
	 * @param suozaidi
	 *            suozaidi
	 */
	public void setSuozaidi(String suozaidi) {
		this.suozaidi = suozaidi;
	}

	/**
	 * suozaidi ���擾���܂�.
	 * 
	 * @return suozaidi
	 */
	public String getSuozaidi() {
		return this.suozaidi;
	}

	/**
	 * tupian ��ݒ肵�܂�.
	 * 
	 * @param tupian
	 *            tupian
	 */
	public void setTupian(String tupian) {
		this.tupian = tupian;
	}

	/**
	 * tupian ���擾���܂�.
	 * 
	 * @return tupian
	 */
	public String getTupian() {
		return this.tupian;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Car other = (Car) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
